image: google/cloud-sdk:alpine

## Beta viersion. You must delete App Engine verions manually to avoid 250 versions limit.

deploy_review:
  stage: deploy
  script:
    - cp $APP_YAML app.yaml
    - cp $ENV .env
    - cp $SERVICE_ACCOUNT /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud builds submit --config .ci/single-project/review/cloudbuild.yaml --project $PROJECT_ID --substitutions _VERSION=$CI_COMMIT_SHORT_SHA
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_COMMIT_SHORT_SHA.staging.$PROJECT_ID.appspot.com
  only:
    - branches
  except:
    - master
after_script:
  - rm /tmp/$CI_PIPELINE_ID.json
