steps:
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: sh
  args: ['.ci/single-project/production/build-front-end.sh']
- name: 'gcr.io/google-appengine/php72'
  entrypoint: sh
  args: ['.ci/single-project/production/build-back-end.sh']
- name: 'gcr.io/google-appengine/php72'
  entrypoint: sh
  args: ['.ci/single-project/production/test.sh']
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: sh
  args: ['.ci/single-project/production/deploy.sh']
timeout: "1600s"
